### ISSUE TITLE
Probelms to upload the gateway example. 

### ISSUE THREAD

**Issue by guillermoamorin** [sparkfunX/ESP32_LoRa_1CH_Gateway#1]
Hi, I am following the next tutorial : 

hhttps://learn.sparkfun.com/tutorials/esp32-lora-1-ch-gateway-lorawan-and-the-things-network?_ga=2.50826346.2118500240.1550669780-1924351644.1507658708#routing-to-the-things-network and I can't even upload the sketch. 

After a few trials, I change the arduino ide board option from "SparkX ESP32 LoRa Gateway" to "Esp 32 Dev Moule" and the upload speed from 921600 to 115200 and I finaly could upload the sketch. 

But when I acces to tthe Serial Monitor, the log it shows repeteadly is:   

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (S.ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10088
load:0x40080400,len:6380
entry 0x400806a4
ESP32 defined, freq=
ARDUINO_ARCH_ESP32 defined
SPIFFS init success
Assert=Do Asserts
debug=1
readConfig:: Starting 
.SSID=	wifing
.PASS=	wifing-pub
.CH=	0
.SF=	9
.FCNT=	0
.DEBUG=	1
.PDEBUG=64
.CAD=1
.HOP=0
.NODE=	0
.BOOTS=	21
.RESETS=	0
.WIFIS=	21
.VIEWS=	0
.REFR=	0
.REENTS=	0
.NTPETIM=	0
.NTPERR=	0
.NTPS=	21
.FILEREC=	0
.FILENO=	0
.FILENUM=	0
.EXPERT=	0
#

MAC: 84:0d:8e:07:56:8c, len=17
WlanConnect:: Init para 0
0:1:3. WiFi connect SSID=wifing, pass=wifing-pub
A WlanStatus:: CONNECTED to wifing
Host esp32-07568c WiFi Connected to wifing on IP=172.16.106.63
Local UDP port=1700
Connection successful
Gateway ID: 840D8EFFFF07568C, Listening at SF9 on 903.90 Mhz.
setupOta:: Started
Ready
IP address: 172.16.106.63
Time: Tuesday 23:45:31
Gateway configuration saved
WWW Server started on port 80
Unknown transceiver=0, pins.rst =27, pins.ss  =16, pins.dio0 =26, pins.dio1 =33, pins.dio2 =32

abort() was called at PC 0x400da1de on core 1

Backtrace: 0x4008c824:0x3ffb1ed0 0x4008ca55:0x3ffb1ef0 0x400da1de:0x3ffb1f10 0x400da4ff:0x3ffb1f30 0x400dcee5:0x3ffb1f50 0x400e754b:0x3ffb1fb0 0x4008eaa5:0x3ffb1fd0

Rebooting...

**Comment by oclyke** [comment]
Hello @guillermoamorin,

Thanks for submitting an issue. I'll try to help you get this working. So first of all I'd like to ask for a little more information. 

> ### Subject of the issue
> Describe your issue here.
> 
> ### Your workbench
> * Arduino IDE Version
> * How is the device wired to your platform?
> * How is everything being powered?
> * Are there any additional details that may help us help you?
> 
> ### Steps to reproduce
> Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.

I also notice that your reset pin is set to 27, when in the [Turning a Gateway Into a Device](https://learn.sparkfun.com/tutorials/esp32-lora-1-ch-gateway-lorawan-and-the-things-network?_ga=2.50826346.2118500240.1550669780-1924351644.1507658708#turning-a-gateway-into-a-device) section, sub-section "Load the Single-Channel Device Example" it shows that the ```.rst``` pin should be 5. I would also double-check that the other configuration options have been successfully transferred into your environment per the tutorial.

Please let me know if that worked and if not then the information above would be very helpful.

**Comment by jeanole** [comment]
issued the same problem using the newer version: things4u/ESP-1ch-Gateway as the linked one was marked as old..
but the pin-mapping didnt work out until i found this in ESP-sc-gateway.ino in 30
````
#if defined (ARDUINO_ARCH_ESP32) || defined(ESP32)
#	define ESP32_ARCH 1
#	ifndef _PIN_OUT
#		define _PIN_OUT 4									// For ESP32 pin-out 4 is default //change pin map
#	endif
#elif defined(ARDUINO_ARCH_ESP8266)
````

you have to put your pin-mapping( the one suggested by sparkfun) in loraMode.h under ''#elif _PIN_OUT==4'' or change the defined _PIN_OUT

**Comment by nseidle** [comment]
Hi folks - we're archiving this older repo and directing issues and comments over to the current [SparkFun version](https://github.com/sparkfun/ESP32_LoRa_1Ch_Gateway). Please open a new issue if you're still having problems.
